version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examthourayas2
    ports:
      - 3307:3307


  spring-boot:
    image: ghazichhida/DEVOPSS
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database

    restart: on-failure